# Generated by Django 5.1.1 on 2024-10-16 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import validations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("counter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Waiting"), (1, "Running"), (2, "Success"), (3, "Failure")]
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("platform_name", models.CharField(blank=True, max_length=150)),
                (
                    "filename",
                    models.CharField(blank=True, help_text="Original filename", max_length=100),
                ),
                (
                    "file",
                    models.FileField(null=True, upload_to=validations.models.validation_upload_to),
                ),
                ("result_data", models.JSONField(null=True)),
                (
                    "validation_result",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, ""),
                            (10, "Passed"),
                            (20, "Notice"),
                            (30, "Warning"),
                            (40, "Error"),
                            (50, "Critical error"),
                            (60, "Fatal error"),
                        ],
                        default=0,
                        help_text="The worst result of all the results in the validation",
                    ),
                ),
                ("memory", models.PositiveBigIntegerField(null=True)),
                ("time", models.FloatField(null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="core.userapikey"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counter.platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("platform__isnull", True), ("platform_name", ""), _connector="OR"
                        ),
                        name="validations_validation_platform_union",
                    )
                ],
            },
        ),
    ]
